---
# Source: opencti/templates/server/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-opencti
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opencti
    app.kubernetes.io/version: 6.2.18
    helm.sh/chart: opencti-1.6.0
    opencti.component: server
automountServiceAccountToken: false
