---
# Source: opencti/charts/minio/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-minio
  namespace: "opencti"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: minio
    app.kubernetes.io/version: 2024.8.29
    helm.sh/chart: minio-14.7.5
type: Opaque
data:
  root-user: "Q2hhbmdlTWU="
  root-password: "Q2hhbmdlTWU="
